### ISSUE TITLE
Question about the new definition std :: jthread

### ISSUE THREAD

**Issue by Jamaika1** [nmcclatchey/ThreadPool#5]
How different is the std::thread from std::jthread?
Does it make sense to change definitions for c++20?
Is std::jthread only under c++20?
I was able to compile std::jthread under c++17. Is it compatible with mingw.thread?
https://github.com/josuttis/jthread

**Comment by nmcclatchey** [comment]
This is not the correct place to ask such a question. You have already asked in the correct location (mingw-std-threads repository), so I will answer it there.
