### ISSUE TITLE
Task Re-entrancy

### ISSUE THREAD

**Issue by tom-leys** [nmcclatchey/ThreadPool#7]
I want a custom way to pop and execute a task from the ThreadPool while "inside" `Worker::execute()`. My current attempt seems to corrupt the queue.

I think my call to `worker->pop` below (this is our thread's own worker) is corrupting the local queue. I'm getting later exceptions trying to call null function objects if I use that code.

Here's the context including my current attempt (which is added to your source file):

---

I'd like a way for a currently executing task to re-enter the ThreadPool, pick up an additional task and execute that task right now. This routine will be called either

1. From the main thread, while waiting for tasks to complete
2. From a worker thread, inside a task - waiting for spawned tasks to complete. 

For case (2) that means we ARE inside `Worker::execute` and likely also inside `ThreadPoolImpl::steal_work` or whatever function name is used here.

For some nice diagrams, see https://software.intel.com/content/www/us/en/develop/documentation/tbb-documentation/top/intel-threading-building-blocks-developer-reference/task-scheduler.html - I'm hoping to implement a simple "Blocking Style"

When we last discussed this, you suggested continuations (with an example, thanks!) and coroutines. Both of these solutions require the user code to "understand" our threading model, where I want to hide it somewhat. I'm porting existing naive code to use a threadpool under C++11 so those solutions are hard.

I've created a simple first-pass implimentation:

```c++
bool ThreadPoolImpl::steal_work()
{
    Worker* worker = current_worker;
    // If a thread is attempting to schedule in its own pool...
    if ((worker != nullptr) && worker->belongs_to(this))
    {
        // Run one of the tasks due to be run in this (our) worker thread
        task_type task;
        if (worker->pop(task)) // <<< I cannot figure out how to do this without corruption
        {
            task();
            return true;
        }
    }
    else if (mutex_.try_lock())
    {
        // Run a task from the general thread-pool
        if (queue_.empty())
        {
            mutex_.unlock();
        }
        else
        {
            task_type task = extract_task();
            mutex_.unlock();
            task();
            return true;
        }
    }

    return false;
}
```

Here is how my threadpool wrapper uses this functionality `m_pool.steal_work()` : 
```c++
// Do useful work until the given future is ready. 
    template< class T >
    void work_until(std::future<T>& wait)
    {
        // If the task is done quickly, just exit.
        if (wait.wait_for(
            std::chrono::milliseconds(1)) == std::future_status::ready)
        {
            return;
        }

        // While there is still waiting to do, do some useful work.
        while(wait.wait_for(std::chrono::seconds::zero()) != std::future_status::ready)
        {            
            if (!m_pool.steal_work())
            {
                if (wait.wait_for(
                    std::chrono::milliseconds(1)) == std::future_status::ready)
                {
                    return;
                }
            }
        }
    }
```

**Comment by nmcclatchey** [comment]
`Worker::pop()` is not designed for use during task execution. The aspect of ThreadPool that is being ignored here is `front_invalid_`. I may be able to refactor the pool to remove this variable, which would potentially enable the kind of task you are aiming for.

I'll look into this, and re-evaluate the logic I had used when deciding on this implementation detail.

**Comment by nmcclatchey** [comment]
To follow up from earlier: In the current implementation, the front of the queue is always reserved for the thread that owns the queue. The variable `front_invalid_` is used to indicate that the current "front" task is being executed, and may safely be overwritten when adding a new task. The `pop()` function is currently never executed from within a task, so it is not designed to interact correctly with `front_invalid_`.

To implement your `steal_work()` function, the `pop()` function will need to be modified. I believe it is possible. I'll post on this issue again when I have worked out the details.

**Comment by tom-leys** [comment]
Thanks @nmcclatchey - I really appreciate how much help you are offering me and so rapidly.

Would you be interested in submission of our threading wrapper classes as an example usage? How can we easily contribute?

**Comment by nmcclatchey** [comment]
You're welcome, @tom-leys . I am indeed interested in any examples you wish to provide. Two methods by which you can contribute an example are:

1. Create a Wiki page in the repository's Wiki (recently enabled), and add a link to it in the Wiki's home page. Once it contains at least one example, I will add text to the README directing users to the Wiki for examples.
2. Create a pull request, adding the example code in a directory `examples` at the top level of the Git repository.

I have updated `Worker::pop()` so that it can be used from inside an active task. I'll check for additional potential issues tomorrow.

EDIT: If you pulled 4eeebbd, please pull again. That commit had introduced a race condition, which I have now fixed.

**Comment by tom-leys** [comment]
Thanks!

I'll test it out in the context of our project later today. 

-Tom

**Comment by tom-leys** [comment]
I meant to mention you resolved the problem immediately! Thanks so much @nmcclatchey
